#!/bin/sh

if [ -f ~/.pm-bust ]; then
  if [ $(find /var/cache/pacman/ -name 'kernel26*' -newer ~/.pm-bust | wc -l) -gt 0 ]; then
    if [ "$1" == "-gui" ]; then
      zenity --question --text "Kernel update detected. Should I shutdown instead?"
      if [ $? -eq 0 ]; then
        shutdown="y"
      else
        shutdown="n"
      fi
    else
      echo "Kernel update detected. Should I shutdown instead? [y/N]"
      read shutdown
    fi

    if [ "$shutdown" == "y" ]; then
      echo "Shutting down.."
    fi

    exit 0
  fi
fi

#touch ~/.pm-bust
echo "Hibernating.."
